### ISSUE TITLE
Continue to serve client side js even if it fails on the server

### ISSUE THREAD

**Issue by Jon-Biz** [Techwraith/ribcage-preview#15]
If there is an error in the component, it halts on the server, which prevents the use of client-side debugging tools. Ideally, an error should be logged out on the server, and the preview should still be delivered to the client, where debugging can be performed.

**Comment by joeybaker** [comment]
maybe we also add a banner to the page with the error?

**Comment by joeybaker** [comment]
Fixed here: https://github.com/Techwraith/ribcage-preview/commit/679d0b0799e4eb24250c67c860bfedf37833d384
